blank_issues_enabled: false
contact_links:
  - name: ExtractMD Website
    url: https://extractmd.miguelcorderocollar.com/
    about: Visit the official ExtractMD website for general information.
  - name: Privacy Policy
    url: https://extractmd.miguelcorderocollar.com/privacy.html
    about: Read our privacy policy to understand how ExtractMD handles your data.
